### ISSUE TITLE
why do you use Cassandra

### ISSUE THREAD

**Issue by MaryLilian** [combit/NETDataProviders#2]
Hi, I am reading your project and I love this project
I have a question, why do you choose Cassandra in your project instead of other NoSQL like Redis, MongoDB , are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Cassandra instead of your project instead of other NoSQL like Redis, MongoDB

**Comment by jbartlau** [comment]
Mary, there's also a Redis Provider (https://github.com/combit/NETDataProviders/tree/main/combit.ListLabel.RedisDataProvider). MongoDB is supported OOTB by the product and doesn't need additional effort. We really don't care about the database backend and try to support as many databases as possible

**Comment by jbartlau** [comment]
See here: [OOTB](https://en.wikipedia.org/wiki/Out_of_the_box_(feature)) 🙂
