### ISSUE TITLE
SchemaAwareJsonDataProvider nuget package

### ISSUE THREAD

**Issue by feelgood-interface** [combit/NETDataProviders#4]
Is it possible that the SchemaAwareJsonDataProvider is published as nuget package?

**Comment by jbartlau** [comment]
Sure - we'll see if we can implement this with the next release 28.002. Your changes from PR3 would then also be contained. I'll keep this issue updated as we progress.

**Comment by DanielKenner** [comment]
The package will be published to nuget.org with release 28.002 and also be included in the setup.
