### ISSUE TITLE
SchemaAwareJson: make LlFieldType configurable

### ISSUE THREAD

**Issue by feelgood-interface** [combit/NETDataProviders#5]
Good day,
would it be possible to add the option to configure `JsonTableColumn.FieldType`?
```
namespace combit.Reporting.DataProviders
{
	public class JsonTableColumn : ITableColumn
	{
		public string ColumnName { get; private set; }

		public Type DataType { get; private set; }

		public object Content { get; private set; }

		public LlFieldType FieldType { get; private set; }

		public JsonTableColumn(string columnName, Type dataType, object content, LlFieldType fieldType = LlFieldType.Unknown)
		{
			ColumnName = columnName;
			DataType = dataType;
			Content = content;
			FieldType = fieldType;
		}
	}
}
```

My use case: I have a property which I annotate with `[JsonSchema(JsonObjectType.File)]`. Then I extend the function `ColumnFromSchemaData()` in `JsonSchemaOnlyTableRow`:
```
if (data.Type.HasFlag(JsonObjectType.File))
{
	return new JsonTableColumn(columnName, typeof(string), null, LlFieldType.Drawing);
}
```
So then I can use this property directly as a `Drawing` (from a filename or base64). I am doing this mainly for backwards compatibility for old LL templates where I was using System.Drawing.Image in my class.

**Comment by jbartlau** [comment]
@feelgood-interface How about using the `AutoDefineField` event of the `ListLabel` class to adjust the field type as required? Documentation is [here](https://docu.combit.net/net/en/combit.ListLabel~combit.Reporting.ListLabel~AutoDefineField_EV.html). That should do the job, and you can choose for which fields you'd like to adjust the type. Would that work for you?
